- name: Facts related to external VPN gateways
  collections:
    - forcepoint.fp_ngfw_smc_ansible
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Retrieve all external GW's
    external_gateway_facts:
  
  - name: Get a specific external GW details
    external_gateway_facts:
      filter: myexternalgateway1
  
  - name: Get a specific external GW, and expand supported attributes
    external_gateway_facts:
      filter: myexternalgateway1
      expand:
        - gateway_profile
        - vpn_site
  
  - name: Retrieve a specific route VPN and format as playbook YAML
    register: results
    external_gateway_facts:
      smc_logging:
        level: 10
        path: ansible-smc.log
      filter: myexternalgateway1
      as_yaml: true

  - name: Write the yaml using a jinja template
    template: src=templates/facts_yaml.j2 dest=./external_gateway_jinja.yml
    vars:
      playbook: external_gateway
      